update cognito users/uuid handling/message groups

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,21 +1,20 @@
 #! /usr/bin/bash
 
-set -e
+set -e # stop if it fails at any point
 
 if [ -z "$1" ]; then
-    echo "No TABLE_NAME argument supplied eg ./bin/ddb/drop cruddur-messages prod"
-    TABLE_NAME=""
-    exit 1
-
+  echo "No TABLE_NAME argument supplied eg ./bin/ddb/drop cruddur-messages prod "
+  exit 1
 fi
 TABLE_NAME=$1
 
 if [ "$2" = "prod" ]; then
-    ENDPOINT_URL""
+  ENDPOINT_URL=""
 else
-    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
+  ENDPOINT_URL="--endpoint-url=http://localhost:8000"
 fi
 
 echo "deleting table: $TABLE_NAME"
+
 aws dynamodb delete-table $ENDPOINT_URL \
---table-name $TABLE_NAME \
+  --table-name $TABLE_NAME
